enum TemplateAccessibility {
    static let signIn = "voice-template.sign-in.apple"
    static let commandField = "voice-template.capture.command-field"
    static let submitCommand = "voice-template.capture.submit"
    static let startVoice = "voice-template.capture.voice.start"
    static let typedFallback = "voice-template.capture.typed-fallback"
    static let entryBodyPrefix = "voice-template.entries.body"
    static let settingsOpen = "voice-template.settings.open"
    static let deleteAccount = "voice-template.settings.account.delete"
    static let homeBrainDumpCard = "journal.home.brain-dump-card"
    static let homeReflectionPrompt = "journal.home.reflection-prompt"
    static let brainDumpStartVoice = "journal.brain-dump.voice.start"
    static let brainDumpWaveform = "journal.brain-dump.waveform"
    static let entryEditBody = "journal.entry-edit.body"
    static let entryEditSave = "journal.entry-edit.save"
}
